Nike-Inc/brickflow

- .github/workflows/codeql-analysis.yml
- .github/workflows/onpush.yml
- brickflow/cli/entrypoint.template
- examples/brickflow_examples/workflows/entrypoint.py
- tests/cli/test_cli.py
Initial setup for github actions
- disabled codeql (only works for public with advanced security enabled)
- disabled codecov push as repo is still private
- ran fmt for examples
> Github actions initial setup

- CODEOWNERS
- README.md
- docs/quickstart.md
- pyproject.toml
The package name in pyproject.toml is changed to Brickflows as pypi is not allowing us to use brickflow.
Error can be found here - 
https://github.com/Nike-Inc/brickflow/actions/runs/5827261247/job/15802969624
> Updating the package name to brickflows as pypi won't accept brickflow

- brickflow/codegen/databricks_bundle.py
- pyproject.toml
- tests/codegen/expected_bundles/local_bundle_prefix_suffix.yml
- tests/codegen/test_databricks_bundle.py
currently BRICKFLOW_WORKFLOW_SUFFIX does not work as expected.
if user deploys the workflow using suffix e.g. _suffix10
`BRICKFLOW_WORKFLOW_SUFFIX=_suffix10 poetry run brickflow deploy --deploy-mode bundle --workflows-dir src/workflows -e local`
then bundle root path would be - /Users/${workspace.current_user.userName}/.brickflow_bundles/test-project/local
if user deploys the same workflow using another suffix e.g. _suffix20
`BRICKFLOW_WORKFLOW_SUFFIX=_suffix poetry run brickflow deploy --deploy-mode bundle --workflows-dir src/workflows -e local`
then it will replace the earlier workflow because bundle root path will be generated again to be -  /Users/${workspace.current_user.userName}/.brickflow_bundles/test-project/local
This fix will create dedicated bundle root path for each suffixes. …
> fix: generate the bundle path including prefix/suffix if available

- brickflow/codegen/databricks_bundle.py
- brickflow/engine/workflow.py
- docs/workflows.md
- tests/codegen/expected_bundles/dev_bundle_monorepo.yml
- tests/codegen/expected_bundles/dev_bundle_polyrepo.yml
- tests/codegen/expected_bundles/dev_bundle_polyrepo_with_auto_libs.yml
- tests/codegen/expected_bundles/local_bundle.yml
- tests/codegen/expected_bundles/local_bundle_prefix_suffix.yml
- tests/engine/test_workflow.py
To give the user authority to decide if the workflow should be paused or unpaused when the workflow is deployed. 
#39 
This will enable users to provide the below options for `schedule_pause_status` in workflow object
`schedule_pause_status = {"paused"|"unpaused"|"PAUSED"|"UNPAUSED"}`
Updated unitests and also tested manually by deploying a workflow in my workspace
> Feature support job schedule pause status

- CONTRIBUTORS.md
- brickflow/engine/compute.py
- docs/workflows.md
- tests/engine/test_compute.py
Make node_type_id optional as it's otherwise impossible to create a cluster from resources in a pool
https://github.com/Nike-Inc/brickflow/issues/43
This would help all teams that are using brickflow and want to run some of their jobs on clusters taking instance from cluster pools for performance, SLA or other reasons
I succesfully deployed my workflow to Databricks where it made use of the instances provided by a pool.
I ran 'make check' to align with the formatting standards.
I ran 'make test' and everything was successfull
When create cluster with instances from pool
```
Cluster(
name="some_cluster_name,
spark_version="any_spark_version",
instance_pool_id="some_instance_pool_id",
num_workers=1,
)
```
and run `brickflow  deploy`  , on wheel containing my commits,  it succeeds
``` …
```
> Make node_type_id optional as it's otherwise impossible to create a cluster from resources in a pool

- brickflow/codegen/databricks_bundle.py
- brickflow/engine/task.py
- brickflow/engine/workflow.py
- docs/workflows.md
- tests/codegen/expected_bundles/dev_bundle_monorepo.yml
- tests/codegen/expected_bundles/dev_bundle_polyrepo.yml
- tests/codegen/expected_bundles/dev_bundle_polyrepo_with_auto_libs.yml
- tests/codegen/expected_bundles/local_bundle.yml
- tests/codegen/expected_bundles/local_bundle_prefix_suffix.yml
- tests/codegen/sample_workflow.py
- tests/engine/sample_workflow.py
- tests/engine/test_workflow.py
Enable health parameters to be passed into workflow and task to set timeout warning notifications
Description
added health option to Workflow class
How Has This Been Tested?
tests updated to cover new functional
dev test by deploying workflows to databricks with health option
Screenshots (if appropriate):
Types of changes
Checklist:
> Add ability to set timeout health check in workflows

- Makefile
- brickflow_plugins/databricks/workflow_dependency_sensor.py
- docs/faq/faq.md
- docs/tasks.md
This PR contains following changes
- Changes to WorkflowDependencySensor such that other secret managers can be used to specify the api token
- Fix bug in WorkflowDependencySensor where start_time_from was in unix seconds i.s.o millisecond
-  Put `--no-autodetect` in make check of Makefile cause otherwise prospector needs django which isn't used. I needed this to get `make check` running on my machine but not sure what you guys think of this
- [Issue 48](https://github.com/Nike-Inc/brickflow/issues/48)
- [Issue 60](https://github.com/Nike-Inc/brickflow/issues/60)
At this point in time the WorkflowDependencySensor doesn't work at all which blocks multiple users of brickflow.
I know that in the future this functionality will not be needed anymore in brickflow as it's become Databricks …
> Fix  issue 48 and 60 related to the WorkflowDependencySensor

- brickflow/engine/task.py
- brickflow_plugins/databricks/uc_to_snowflake_operator.py
- docs/faq/faq.md
- docs/tasks.md
- examples/brickflow_examples/workflows/demo_wf.py
- tests/codegen/expected_bundles/dev_bundle_polyrepo_with_auto_libs.yml
- tests/engine/test_task.py
Added code to handle authenticator issue posted in issue #85 
Added snowflake library installation to avoid initialization failures for brickflow plugins 
enhanced the code to accept parameters based on load_type instead of making every parameter mandatory. 
fix #85 
At this point code is failing for user id's which require extra authentication mechanism which is blocking multiple brickflow consumers. As we added snowflake operator to initialize with brickflow_plugins it is looking for snowflake library and causing issues to some customers, fixing this issue. Current version of the operator expects optional parameters like sf_cluster_keys, incremental_filter, sf_grantee_roles even when they are not required for customers and causing issues. 
Created a wheel file , workflow and tested with …
> added fix for snowflake operator to accept authenticator and make parameters optional based on load_type

- CONTRIBUTORS.md
- brickflow_plugins/airflow/operators/external_tasks.py
Closes #88 
The date/time parsing in AutosysSensor is format sensitive. We can use `dateutil.parser` to make the process format agnostic.
Using the `dateutil.parser` to make internal logic of AutosysSensor agnostic to the format of the `execution_date` provided by the Brickflow context; and using the same approach to parse `lastEndUTC` string to timestamp.
[[BUG] Faulty execution_date parser in AutosysSensor](https://github.com/Nike-Inc/brickflow/issues/88)
This solves the cases when/if upstream Autosys API changes and the `lastEndUTC` timestamp is provided in different format;
It solved error when parsing the `execution_date` which format may be different depending on how the job is triggered.
> [BUG] Change date/time parsing in AutosysSensor

- CONTRIBUTORS.md
- brickflow_plugins/airflow/operators/external_tasks.py
Closes #86 
Making authentication optional for AutosysSensor. If `airflow_cluster_auth` is provided, it will be used to obtain the authentication token. The token then will be included in the request headers. Otherwise the call will happen without auth.
[[FEATURE] Optional authentication for AutosysSensor](https://github.com/Nike-Inc/brickflow/issues/86)
Skip authentication token acquisition if it's not required, reduces the amount of calls to the credentials store and / or authentication service, eg. Okta. Streamlines and simplifies user experience.
Built wheel with the change, used wheel as a cluster library instead of the original brickflow distribution from PyPi. Executed workflow with AutosysSensor both with and without authentication. Both scenarios succeeded.
> [FEATURE] Optional auth for AutosysSensor

- brickflow/codegen/databricks_bundle.py
Closes #106 
Adding custom representer for yaml.dump to ensure that string values are enclosed in the quotation marks.
#106 
If any string value in the generated `bundle.yaml` can be interpretted as something other than a string, e.g. number in scientific notation, deployment to Databricks may / will fail. It definitly guarantees failed deployment when this case occurs for `policy_id` for cluster.
I've used local installation of brickflow with this change to generate the updated bundle and successfully deployed it Databricks. Workflow was successfully created with the correct cluster setup and any other expected configuration.
> [FIX] Cluster `policy_id` converted to scientific notation

- brickflow/engine/task.py
- tests/engine/test_task.py
Clean user input to `brickflow_internal_only_run_tasks` parameter:
- trim whitespaces
- allow valid JSON list as input
#105 
Usability improvement
Unit tests
> [FEATURE] Sanitise input of the `brickflow_internal_only_run_tasks` parameter

- brickflow/engine/utils.py
- brickflow_plugins/__init__.py
- brickflow_plugins/databricks/workflow_dependency_sensor.py
- docs/api/workflow_dependency_sensor.md
- docs/faq/faq.md
- docs/tasks.md
- poetry.lock
- pyproject.toml
- tests/databricks_plugins/test_workflow_task_dependency_sensor.py
- tests/engine/test_utils.py
Leverage Databricks API to retrieve the state of the specific task within the workflow run. The code mostly inherits from the `WorkflowDependencySensor`.
#109 
In many cases it's more benificial to put a dependency on a specific task within the workflow instead the workflow itself. It reduces the wait time of the downstream workflows.
Unit tests + workflow in Databricks with a success sensor and a failed sensor
> [FEATURE] Add `WorkflowTaskDependencySensor`

- brickflow_plugins/airflow/operators/external_tasks.py
- tests/airflow_plugins/test_autosys.py
Handle the situations where `lastEndUTC` data is None plus add tests to test the overall logic and error handling.
#112 
Operator is failing if `lastEndUTC` is empty.
A set of local tests has been implemented + used custom wheel in the workflow
> [fix] AutosysSensor: Handle the situations where `lastEndUTC` is empty or None

- brickflow_plugins/databricks/workflow_dependency_sensor.py
- tests/databricks_plugins/test_workflow_task_dependency_sensor.py
Check if `task_state` is not None, otherwise log and continue poking.
#122 
The sensor will otherwise fail if the task execution has not yet started (e.g. the task is in Pending state)
TDD
> [fix] WorkflowTaskDependecySensor fails if the task execution has not started

- brickflow_plugins/airflow/operators/external_tasks.py
- tests/airflow_plugins/test_task_dependency.py
These changes are in line with the reasoning that's described in #101.
1. Make sensor results repeatable if workflow is restarted by using the `execution_date` which is derived from Brickflow context and not the current time. This ensures that relative delta between the workflow run (based on it's schedule) and the upstream DAG run always stays the same.
2. Sensor will always poke upstream, unless timeout is reached. This ensure that if upstream is failed or running, or in some other state, the sensor will continue waiting for the `success` (by default)
#101 
Improve sensor stability and simplify workflow reruns.
Unit tests + this code had been overriding the original sensor and running in production pipelines
> TaskDependencySensor: do not fail if upstream failed / derive execution time from context

- brickflow/engine/task.py
- brickflow/engine/workflow.py
- brickflow_plugins/databricks/run_job.py
- docs/tasks.md
- tests/codegen/expected_bundles/dev_bundle_monorepo.yml
- tests/codegen/expected_bundles/dev_bundle_polyrepo.yml
- tests/codegen/expected_bundles/dev_bundle_polyrepo_with_auto_libs.yml
- tests/codegen/expected_bundles/local_bundle.yml
- tests/codegen/expected_bundles/local_bundle_prefix_suffix.yml
- tests/codegen/sample_workflow.py
- tests/codegen/test_databricks_bundle.py
- tests/databricks_plugins/test_run_job.py
- tests/engine/sample_workflow.py
- tests/engine/test_project.py
- tests/engine/test_utils.py
- tests/engine/test_workflow.py
Databricks does not natively support riggering the job run in the remote workspace. This feature implements the logic that either creates a native RunJobTask or leverages the new RunJobInRemoteWorkspace plugin to execute both local and remote workspace job runs. The functionality does not require any additional parameters, and leverage the `host` parameter of the RunJobTask with the assumtion that if host is provided, user wants remote run. If / when Databricks implements this functionality natively, the code can be removed, but existing workflows won't require any changes.
If host is not provided, Databricks SDK will retrieve host and token for the DEFAULT profile.
#139 
Unit tests, custom workflow
> [FEATURE] Support remote workspace for RunJobTask

- brickflow/codegen/databricks_bundle.py
- tests/codegen/expected_bundles/local_bundle_continuous_schedule.yml
- tests/codegen/sample_workflows.py
- tests/codegen/test_databricks_bundle.py
Runtime and default tags were not applied to cluster
Unit test
Integration test on Databricks environment
> propogate workflow tags to cluster tags

- CONTRIBUTORS.md
- brickflow_plugins/airflow/operators/external_tasks.py
- tests/airflow_plugins/test_task_dependency.py
Add optional parameter of max end date for TaskDependcySensor get_execution_stats(). This is a minor change in order to not introduce a breaking change. However, if you agree I think it is more beautiful to have: 1) a function that returns the latest state of the run to be used for the 'poking' sensor, and have another 2) functionality that allows to query the API in a more flexible manner and allows to return more from the json response. 
This way we are more flexible, so we can use the start/end/state details to trigger different paths in the Brickflow DAGs (with IfElseConditionTask tasks) for instance. E.g. if the Airflow dependency was finished before time x, then branch in this direction, otherwise y direction. Or if latest run had status 'failed', then branch in direction z etc. …
> Allow optional end-date in get_execution_stats()

- brickflow/codegen/databricks_bundle.py
- tests/codegen/expected_bundles/dev_bundle_monorepo.yml
- tests/codegen/expected_bundles/dev_bundle_polyrepo.yml
- tests/codegen/expected_bundles/dev_bundle_polyrepo_with_auto_libs.yml
- tests/codegen/expected_bundles/local_bundle.yml
- tests/codegen/expected_bundles/local_bundle_prefix_suffix.yml
When a task of `NotebookTask` type is used, it does not inherit the common parameters defined in the Workflow in `common_task_parameter`. This PR updates the codegen module in order to propagate these parameters from the workflow into the notebook task.
https://github.com/Nike-Inc/brickflow/issues/99
See issue above.
Existing test cases have been updated.
> [BUG] Missing common task parameters for Notebook Task

- brickflow_plugins/databricks/uc_to_snowflake_operator.py
- docs/faq/faq.md
- docs/tasks.md
Current behavior of SnowflakeOperator does not fail when it hits a SQL error. 
Adds a `fail_on_error` parameter that defaults to `True`, so that the operator will raise exceptions and fail by default, but users can set it to `False` to keep the current behavior for whatever use case they have.
Also made some adjustments to close the connection instead of the cursor, and log the stacktrace if `fail_on_error=False`.
I noticed that the operator was returning success and not logging the error when a query failed to run on snowflake.
Tested in 14.3-LTS
> Add fail_on_error parameter to SnowflakeOperator

- brickflow/cli/projects.py
- brickflow/codegen/databricks_bundle.py
This PR solves https://github.com/Nike-Inc/brickflow/issues/182.  
[PR](https://github.com/Nike-Inc/brickflow/pull/175) introduced support for .yaml extension in project conf files. Because of a wrong defaults in MultiProjectManager (in combination with not providing the config file type in one of instance creation of MultiProjectManager), brickflow was trying to resolve .yaml config files instead of .yml
Deployments from examples with both .yaml and .yml extensions
> [BUG] 182 - Fix brickflow deploy

- brickflow/context/context.py
- tests/context/test_context.py
Catching IndexError exception in context's `get_project_parameter` function.
Fixes #194 
See #194
Added a new unit test to cover scenario when no ENV variable `BRICKFLOW_PROJECT_PARAMS` is provided.
> [fix] issue 194: Uncaught exception IndexError when calling get_project_parameter

- brickflow/engine/compute.py
Missing data security modes have been added as configuration options for clusters
https://github.com/Nike-Inc/brickflow/issues/184
Users could override the data security mode when configuring clusters, but picking values from an enum is a more convenient option
Deployments with all entries in the enum
> [FIX] - 184 Add missing data security modes

- brickflow/cli/bundles.py
- brickflow/cli/projects.py
- tests/cli/test_bundles.py
`bf projects deploy` and `bf projects destroy` can now be run in debug mode.
> [!NOTE]
> As a subsidiary part of this feature, `bf projects deploy` now also supports the `--auto-approve` flag (which `bf projects destroy` already does), to keep up with the related Databricks CLI version.
https://github.com/Nike-Inc/brickflow/issues/200
Currently, the debug mode is only supported for `bf projects sync`. And given that the `debug` option is a global Databricks CLI flag, we should leverage it for `bf projects deploy` and `bf projects destroy` too (handy for troubleshooting).
Unit & integration tests
N/A
> [FEATURE] Enhance support for debug mode

- brickflow/codegen/databricks_bundle.py
- brickflow/engine/task.py
- docs/tasks.md
- tests/codegen/sample_workflows.py
- tests/engine/test_task.py
This PR avoids executing brickflow type for each tasks during bundle generation.
When configuring a for each task, it is not required to provide a nested task type as the builder function simply executes the callable to get in return the task object. This is then used to detect the nested task type and resolve the nested task builder function. While this works out fine with other task types, as brickflow tasks do not return an associated task object, this behaviour was causing the task to be executed during deployment.
To solve that, this PR adds an optional `task_type` attribute in the for each task model to make the builder function aware of the type preventing it to run it if type is indeed brickflow.
This PR targets a patch release: users currently experiencing this issue can start …
> [BUG] 222 - For each task executes nested brickflow task during deployment

- brickflow/cli/bundles.py
- brickflow/cli/projects.py
- tests/cli/test_bundles.py
`bf projects deploy` now accepts a `fail-on-active-runs` flag.
> [!IMPORTANT]
> Even when the aforementioned flag is on, the deployment might fail in some _edgy_ cases, particularly when the bundle includes wheel artifacts. This is not specific to the flag itself, but rather to closely-related internals of the CLI (fixed as of 0.249.0). 
https://github.com/Nike-Inc/brickflow/issues/232
Deploying a bundle when there are bound resources (e.g. jobs) running at the same time can be disruptive. Hence adding support for the `fail-on-active-runs` flag, which is already supported by the Databricks CLI.
Unit & integration tests
N/A
> Add support for fail-on-active-runs flag

- brickflow/cli/bundles.py
- docs/workflows.md
- tests/cli/test_bundles.py
Fixed architecture detection for ARM64 Linux machines by improving the `get_arch()` function in `bundles.py`. The function now correctly handles multiple architecture identifiers and returns standardized architecture strings for the Databricks CLI download URL.
- Updated architecture mapping to handle both `arm64` and `aarch64` identifiers
- Improved test coverage using parametrized tests to verify all architecture mappings
- Added case insensitivity handling for architecture detection
- Added explicit error handling for unsupported architectures
Also update docs to add explanation for `queue` in workflows
#94 
This fix ensures correct CLI bundle downloads on ARM64 Linux machines, particularly when `platform.machine()` returns "aarch64" instead of "arm64".
Unit Testing
> Fixing a bug, including aarch64

- brickflow/codegen/databricks_bundle.py
- tests/codegen/expected_bundles/dev_bundle_polyrepo_with_auto_libs.yml
- tests/codegen/expected_bundles/local_bundle_foreach_task.yml
- tests/codegen/expected_bundles/local_serverless_bundle.yml
Workflow could not be configured without health rules as it was failing validation. Now if health rules are not set, the corresponding property will be set to None instead.
https://github.com/Nike-Inc/brickflow/issues/244
Unit tests and manual deployments with both health rules provided and not provided.
> [BUG] 244 - Cannot deploy workflow without health rule
