Nike-Inc/brickflow

.gitignore, README.md
Adding Badges for build, codecov etc
=> Adding github badges

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/PULL_REQUEST_TEMPLATE.md
Adding Issue Templates and pull Request Templates!
=> Adding pull request and issue templates

README.md, brickflow/cli/entrypoint.template
Fixing the issue in the entrypoint file. Updating the readme documentation
#34
When the user creates a new brickflow project using “bf projects add”, the entrypoint contains brickflow version which is not required and redundant. If the version is chosen as “auto” by the user, then it’s add pip installation version as auto, which will eventually fail.
Local unittesting
=> Addressing the issue - #34

brickflow_plugins/airflow/operators/external_tasks.py, docs/tasks.md, examples/brickflow_examples/workflows/demo_wf.py
=> Updated TaskDependency Sensor to account for execution delta and enabled logging for debugging purposes 

CONTRIBUTORS.md, README.md, brickflow_plugins/airflow/operators/external_tasks.py, examples/brickflow_examples/workflows/demo_wf.py
Adding new contributors and update  readme
NA
NA
Just document updates
NA
=> updating contributors and read me

docs/tasks.md, pyproject.toml
Fixed the Title for autosys sensor in documentation
=> Fix: Title for autosys sensor in documentation

CONTRIBUTORS.md
Updating new contributors
No significant changes. updating contributors.md
No tests required
=> updating contributors

brickflow/bundles/model.py, brickflow/codegen/databricks_bundle.py, brickflow/engine/workflow.py, docs/workflows.md, tests/codegen/expected_bundles/dev_bundle_monorepo.yml, tests/codegen/expected_bundles/dev_bundle_polyrepo.yml, tests/codegen/expected_bundles/dev_bundle_polyrepo_with_auto_libs.yml, tests/codegen/expected_bundles/local_bundle.yml, tests/codegen/expected_bundles/local_bundle_prefix_suffix.yml, tests/codegen/sample_workflow.py, tests/engine/sample_workflow.py, tests/engine/test_task.py, tests/engine/test_workflow.py
Enable workflow timeout parameters to be passed into workflow and task to set timeout warning notifications
Description
added timeout option to Workflow class
How Has This Been Tested?
tests updated to cover new functionality
dev test by deploying workflows to databricks with timeout_seconds
Screenshots (if appropriate):
Types of changes
Checklist:
=> Add timeout parameter to workflow class

brickflow_plugins/airflow/operators/external_tasks_tableau.py
Throwing an error with resolution instructions for installation of the `tableauserverclient`.
Closes #103 
Give an easy to follow solution for end users without forcing specific library version.
Uninstalled TSC library - got expected error. Installed TSC library - got OK.
=> Throw an error when `tableauserverclient` is not found with resolution instructions

brickflow/engine/utils.py, brickflow_plugins/databricks/uc_to_snowflake_operator.py, docs/tasks.md, examples/brickflow_examples/src/sql/sample.sql, examples/brickflow_examples/workflows/demo_wf.py, tests/engine/test_utils.py
Update Snowflake and UctoSnowflakeOperator Operators to accept sql file and custom db_sql queries as inputs
>
It is an enhancement to pass sql_file to Snowflake Operator and custom sql to extract data from Unity catalog.
Below are the changes implemented as part of this PR
1. sql_file parameter is added to SnowflakeOperator ( File path is relative to brickflow_root)
2. Raise an exception if both query_string and sql_file is passed
3. Add an additional parameter dbx_sql to UcToSnowflakeOperator to use custom sql when extracting data from Unity Catalog
4. Update Mandatory keys to expect one Of dbx_sql or (dbx_catalog, dbx_database, dbx_table)
5. Add an additional (optional) parameter write_mode to specify while writing to Snowflake from Unity Catalog
6. Add additional function to get …
=> Add sql file path to Snowflake Operator and add custom sql for UctoSnowflakeOperator

.github/workflows/onpush.yml
Fixing the python version fix
NA
Deployments to pypi are failing
It is already working in test-pipeline job
=> updating to fix python deployment

brickflow/cli/bundles.py
#219 #189 
Proper deployment of single node cluster
Run existing tests
=> [fix] Update Brickflow CLI version to 0.236.0 in bundle_synth

brickflow/__init__.py, brickflow/codegen/databricks_bundle.py, brickflow/engine/task.py, brickflow/engine/workflow.py, docs/tasks.md, examples/brickflow_examples/workflows/demo_wf.py, tests/codegen/expected_bundles/dev_bundle_monorepo.yml, tests/codegen/expected_bundles/dev_bundle_polyrepo.yml, tests/codegen/expected_bundles/dev_bundle_polyrepo_with_auto_libs.yml, tests/codegen/expected_bundles/local_bundle.yml, tests/codegen/expected_bundles/local_bundle_prefix_suffix.yml, tests/codegen/sample_workflows.py, tests/codegen/test_databricks_bundle.py, tests/engine/test_task.py
Added PythonWheelTask, to enable support for using [python wheels to submit jobs on a databricks workflow](https://docs.databricks.com/aws/en/jobs/how-to/use-python-wheels-in-workflows#step-5-create-a-databricks-job-to-run-the-python-wheel-file). 
https://github.com/Nike-Inc/brickflow/issues/15
Some users have requested this functionality as it is native to databricks workflows.
Created a local workflow using an existing whl
With dev SP:
=> Add PythonWheelTask

brickflow_plugins/airflow/operators/external_tasks_tableau.py, tests/airflow_plugins/test_tableau.py
Handle multiple projects error, when one of the projects is in root.
#141 
Unit tests
=> [fix] Add root parent project support for Tableau operators

brickflow/codegen/databricks_bundle.py, brickflow/engine/workflow.py, tests/codegen/test_databricks_bundle.py
Added queue variable to workflows
adds the support for queueing by workflows explicitly. DABs enables by default and it is good to typically have queueing on.
There are unit tests
=> Feature queueing workflows

pyproject.toml
add comment to `pyproject.toml` with explanation why python version is below 3.12
Prevent other new users to ask why Python version is below 3.12.
=> add comment why python version < 3.12

brickflow/codegen/databricks_bundle.py, tests/codegen/expected_bundles/dev_bundle_polyrepo_with_auto_libs.yml, tests/codegen/expected_bundles/local_bundle_foreach_task.yml, tests/codegen/expected_bundles/local_serverless_bundle.yml, tests/codegen/sample_workflows.py
Fix jobs health type during bundle generation
[ISSUE](https://github.com/Nike-Inc/brickflow/issues/209)
Jobs health rules could not get configured because of the incorrect type being used in the jobs  
- unit tests
- manual deploy
=> [FIX] 209 - Workflow jobs health type 

.github/workflows/onpush.yml
Making sure that project components and plugins pass the tests on all supported Python versions.
=> Run `onpush` workflow on multiple python versions

brickflow/codegen/databricks_bundle.py, brickflow/engine/workflow.py, docs/tasks.md
I've used the code from the original PR from @stikkireddy: https://github.com/Nike-Inc/brickflow/pull/227/files
Plus updated the documentation, fixed a failing test and validated once again that this approach does indeed work.
=> Support intra-project workflow references for RunAsJob

brickflow/engine/task.py, tests/codegen/expected_bundles/dev_bundle_polyrepo_with_auto_libs.yml, tests/databricks_plugins/test_sla_sensor.py, tests/databricks_plugins/test_workflow_dependency_sensor.py, tests/databricks_plugins/test_workflow_task_dependency_sensor.py, tests/test_plugins.py
Mandatory libraries that Brickflow deploys when plugins are enabled are out of sync with the (dev)dependencies specified in the project and executed in tests. 
https://github.com/Nike-Inc/brickflow/issues/248
Unit tests; Test workflow on DBR 13.x / 15.x / 16.x
=> [bugfix] Sync library versions for plugins with dev dependencies
